# PyTorch Tensors

A tensor is the main data structure used by PyTorch.

A tensor is a multi-dimensional array that can store numbers.

Tensors are used to represent:

- Input data
- Features
- Labels
- Weights
- Biases
- Images
- Audio
- Text representations
- Neural network outputs

PyTorch performs mathematical operations on tensors
and can move tensors to the GPU for faster computation.

In [2]:
import torch

print(torch.__version__)

2.11.0+cu128


## Scalar

A scalar is a tensor containing a single value.

Example:

5

A scalar has:

- 0 dimensions
- Shape: []

In [3]:
x = torch.tensor(5)

print(x)
print("Shape:", x.shape)
print("Dimensions:", x.ndim)

tensor(5)
Shape: torch.Size([])
Dimensions: 0


## Vector

A vector is a one-dimensional tensor.

Example:

[10, 20, 30, 40]

It has one dimension.

In [4]:
x = torch.tensor([10, 20, 30, 40])

print(x)
print("Shape:", x.shape)
print("Dimensions:", x.ndim)

tensor([10, 20, 30, 40])
Shape: torch.Size([4])
Dimensions: 1


## Matrix

A matrix is a two-dimensional tensor.

It contains rows and columns.

Example:

[[1, 2, 3],
 [4, 5, 6]]

In [5]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x)

print("Shape:", x.shape)
print("Dimensions:", x.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Dimensions: 2


## 3D Tensor

A 3D tensor contains multiple matrices.

Example:

[
    [
        [1, 2],
        [3, 4]
    ],

    [
        [5, 6],
        [7, 8]
    ]
]

Shape:

(2, 2, 2)

In [6]:
x = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    
    [
        [5, 6],
        [7, 8]
    ]
])

print(x)

print("Shape:", x.shape)
print("Dimensions:", x.ndim)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Dimensions: 3


## Tensor Shape

Shape tells us the size of a tensor along each dimension.

For example:

X.shape = (1000, 10)

This means:

1000 → number of samples
10   → number of features

This is exactly the type of tensor used as input
to an ANN.

In [7]:
X = torch.randn(1000, 10)

print(X.shape)

torch.Size([1000, 10])


## Tensor Data Types

PyTorch tensors can contain different data types.

Common types:

- torch.float32
- torch.float64
- torch.int32
- torch.int64
- torch.bool

For neural network calculations, float32 is commonly used.

In [8]:
x = torch.tensor([1.0, 2.0, 3.0])

print(x)
print(x.dtype)

tensor([1., 2., 3.])
torch.float32


In [9]:
# Tensor from values
x = torch.tensor([1, 2, 3])

# Tensor filled with zeros
zeros = torch.zeros(2, 3)

# Tensor filled with ones
ones = torch.ones(2, 3)

# Random tensor
random = torch.rand(2, 3)

print(x)
print(zeros)
print(ones)
print(random)

tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9576, 0.8964, 0.1943],
        [0.5009, 0.9677, 0.3910]])
