# Tensor

A Tensor is a multidimensional array used by TensorFlow
to represent and process data.

In deep learning, tensors are used to store:

- Input data
- Weights
- Biases
- Predictions
- Images
- Text representations
- Model outputs

TensorFlow performs most mathematical operations using tensors.

# Tensor Dimensions

Tensors can have different numbers of dimensions.

0D Tensor → Scalar
1D Tensor → Vector
2D Tensor → Matrix
3D Tensor → 3D Tensor
4D Tensor → 4D Tensor

The number of dimensions is also called the tensor's rank.

import tensorflow as tf

scalar = tf.constant(10)

vector = tf.constant([10, 20, 30])

matrix = tf.constant([
    [1, 2],
    [3, 4]
])

tensor_3d = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("Scalar:")
print(scalar)

print("\nVector:")
print(vector)

print("\nMatrix:")
print(matrix)

print("\n3D Tensor:")
print(tensor_3d)

In [2]:
import tensorflow as tf

scalar = tf.constant(10)

vector = tf.constant([10, 20, 30])

matrix = tf.constant([
    [1, 2],
    [3, 4]
])

tensor_3d = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("Scalar:")
print(scalar)

print("\nVector:")
print(vector)

print("\nMatrix:")
print(matrix)

print("\n3D Tensor:")
print(tensor_3d)

Scalar:
tf.Tensor(10, shape=(), dtype=int32)

Vector:
tf.Tensor([10 20 30], shape=(3,), dtype=int32)

Matrix:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

3D Tensor:
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


# 0D Tensor — Scalar

A scalar contains a single value.

Example:

10

It has:

Rank = 0
Shape = ()

In [3]:
scalar = tf.constant(10)

print("Value:", scalar)
print("Rank:", tf.rank(scalar).numpy())
print("Shape:", scalar.shape)

Value: tf.Tensor(10, shape=(), dtype=int32)
Rank: 0
Shape: ()


# 1D Tensor — Vector

A vector contains multiple values in one dimension.

Example:

[10, 20, 30, 40]

It has:

Rank = 1
Shape = (4,)

In [4]:
vector = tf.constant([10, 20, 30, 40])

print("Vector:", vector)
print("Rank:", tf.rank(vector).numpy())
print("Shape:", vector.shape)

Vector: tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)
Rank: 1
Shape: (4,)


# 2D Tensor — Matrix

A matrix contains rows and columns.

Example:

[
    [1, 2, 3],
    [4, 5, 6]
]

It has:

2 rows
3 columns

Rank = 2
Shape = (2, 3)

In [5]:
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print("Rank:", tf.rank(matrix).numpy())
print("Shape:", matrix.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Rank: 2
Shape: (2, 3)


# 3D Tensor

A 3D tensor contains multiple matrices.

Example:

[
    [
        [1, 2],
        [3, 4]
    ],

    [
        [5, 6],
        [7, 8]
    ]
]

Shape:

(2, 2, 2)

Rank = 3

In [6]:
tensor_3d = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(tensor_3d)
print("Rank:", tf.rank(tensor_3d).numpy())
print("Shape:", tensor_3d.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Rank: 3
Shape: (2, 2, 2)


# Tensors and Images

Images are commonly represented as tensors.

A color image can have the shape:

(height, width, channels)

For example:

(224, 224, 3)

Where:

224 = Height
224 = Width
3 = RGB color channels

The three channels are:

Red
Green
Blue

# Batch of Images

When multiple images are processed together, we commonly use
a 4D tensor:

(batch_size, height, width, channels)

Example:

(32, 224, 224, 3)

Where:

32 = Number of images
224 = Height
224 = Width
3 = RGB channels

# Tensor Shape

Shape tells us the size of each dimension of a tensor.

Example:

X.shape = (100, 5)

This means:

100 → Samples
5 → Features

Therefore, the dataset contains:

100 samples
5 features

In [7]:
X = tf.constant([
    [1., 2., 3.],
    [4., 5., 6.],
    [7., 8., 9.]
])

print("Shape:", X.shape)

Shape: (3, 3)


# Tensor Data Types

Tensors have a data type.

Common TensorFlow data types include:

tf.int32
tf.int64
tf.float32
tf.float64
tf.bool

Deep learning models commonly use:

float32

In [8]:
tensor = tf.constant(
    [1.0, 2.0, 3.0],
    dtype=tf.float32
)

print(tensor)
print("Data type:", tensor.dtype)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Data type: <dtype: 'float32'>
