# Tensor Operations

TensorFlow provides many operations for manipulating and
performing mathematical calculations on tensors.

Important tensor operations include:

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication
6. Exponentiation
7. Sum
8. Mean
9. Maximum
10. Minimum
11. Reshaping
12. Concatenation
13. Stacking
14. Transpose
15. Type Conversion

These operations are fundamental to neural network computations.

# Creating Tensors

Before performing operations, we need tensors.

TensorFlow provides:

tf.constant()
tf.zeros()
tf.ones()
tf.random.normal()
tf.random.uniform()

In [19]:
import tensorflow as tf

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print("A:", a)
print("B:", b)

A: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
B: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


# Tensor Addition

Two tensors with compatible shapes can be added element by
element.

Example:

[1, 2, 3]
+
[4, 5, 6]

=

[5, 7, 9]

In [20]:
result = tf.add(a, b)

print(result)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


# Tensor Subtraction

Tensor subtraction is performed element by element.

Example:

[4, 5, 6]
-
[1, 2, 3]

=

[3, 3, 3]

In [21]:
result = tf.subtract(b, a)

print(result)

tf.Tensor([3 3 3], shape=(3,), dtype=int32)


# Element-wise Multiplication

Element-wise multiplication multiplies corresponding elements.

Example:

[1, 2, 3]
×
[4, 5, 6]

=

[4, 10, 18]

In [22]:
result = tf.multiply(a, b)

print(result)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


# Tensor Division

Division is also performed element by element.

In [23]:
a = tf.constant([10.0, 20.0, 30.0])
b = tf.constant([2.0, 4.0, 5.0])

result = tf.divide(a, b)

print(result)

tf.Tensor([5. 5. 6.], shape=(3,), dtype=float32)


# Matrix Multiplication

Matrix multiplication is one of the most important operations
in neural networks.

TensorFlow provides:

tf.matmul()

For a neural network layer, we commonly have:

Z = XW + b

Where:

X = Input
W = Weight Matrix
b = Bias
Z = Weighted Sum

In [24]:
X = tf.constant([
    [1.0, 2.0],
    [3.0, 4.0]
])

W = tf.constant([
    [0.5, 0.2],
    [0.1, 0.7]
])

result = tf.matmul(X, W)

print(result)

tf.Tensor(
[[0.7 1.6]
 [1.9 3.4]], shape=(2, 2), dtype=float32)


# Exponentiation

Exponentiation raises each tensor element to a power.

In [25]:
x = tf.constant([1.0, 2.0, 3.0])

result = tf.pow(x, 2)

print(result)

tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)


# Square Root

TensorFlow provides:

tf.sqrt()

to calculate the square root of tensor elements.

In [26]:
x = tf.constant([1.0, 4.0, 9.0, 16.0])

result = tf.sqrt(x)

print(result)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


# Absolute Value

tf.abs() returns the absolute value of each element.

In [27]:
x = tf.constant([-5.0, -2.0, 0.0, 3.0, 7.0])

result = tf.abs(x)

print(result)

tf.Tensor([5. 2. 0. 3. 7.], shape=(5,), dtype=float32)


# Sum

tf.reduce_sum() calculates the sum of tensor elements.

In [28]:
x = tf.constant([1, 2, 3, 4, 5])

result = tf.reduce_sum(x)

print(result)

tf.Tensor(15, shape=(), dtype=int32)


# Mean

tf.reduce_mean() calculates the average of tensor elements.

In [29]:
x = tf.constant([10.0, 20.0, 30.0, 40.0])

result = tf.reduce_mean(x)

print(result)

tf.Tensor(25.0, shape=(), dtype=float32)


# Maximum

tf.reduce_max() finds the largest value.

In [30]:
x = tf.constant([10, 5, 30, 15, 20])

result = tf.reduce_max(x)

print(result)

tf.Tensor(30, shape=(), dtype=int32)


# Minimum

tf.reduce_min() finds the smallest value.

In [31]:
x = tf.constant([10, 5, 30, 15, 20])

result = tf.reduce_min(x)

print(result)

tf.Tensor(5, shape=(), dtype=int32)


# Argmax

tf.argmax() returns the index of the largest value.

Example:

[10, 50, 20]

The largest value is:

50

Its index is:

1

In [32]:
x = tf.constant([10, 50, 20])

index = tf.argmax(x)

print(index.numpy())

1


# Reshape

tf.reshape() changes the shape of a tensor without changing
the number of elements.

Example:

Shape:

(2, 3)

Can become:

(3, 2)

Both contain:

6 elements.

In [33]:
x = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(x)

reshaped = tf.reshape(x, (3, 2))

print("\nReshaped:")
print(reshaped)

Original:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Reshaped:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# Transpose

Transpose swaps the dimensions of a tensor.

For a matrix:

Shape:

(2, 3)

After transpose:

Shape:

(3, 2)

In [34]:
x = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

result = tf.transpose(x)

print(result)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


# Concatenation

Concatenation joins tensors together along an existing axis.

Tensor A:

[1, 2, 3]

Tensor B:

[4, 5, 6]

Concatenation:

[1, 2, 3, 4, 5, 6]

In [35]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

result = tf.concat([a, b], axis=0)

print(result)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


# Stacking

tf.stack() combines tensors by creating a new dimension.

In [36]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

result = tf.stack([a, b])

print(result)
print("Shape:", result.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
