# Vectors and Matrices for Deep Learning

Deep Learning uses linear algebra heavily.

Neural networks represent data using:

- Scalars
- Vectors
- Matrices
- Tensors

These mathematical structures are used for:

- Storing input data
- Storing weights
- Storing biases
- Matrix multiplication
- Forward propagation
- Backpropagation
- Image processing
- CNNs
- Transformers

The most important concepts for Deep Learning are:

1. Vectors
2. Matrices
3. Matrix multiplication
4. Dot product
5. Transpose
6. Shapes and dimensions
7. Weights and biases

## 1. Scalar

A scalar is a single number.

Examples:

5
10
-3
0.5

In Deep Learning, examples of scalars include:

- Learning rate
- Loss value
- Bias of a single neuron
- Individual weight

In [1]:
x = 5

print(x)
print(type(x))

5
<class 'int'>


## 2. Vector

A vector is a collection of numbers arranged in one dimension.

Example:

[2, 4, 6]

This vector contains 3 values.

In Machine Learning, a vector can represent the features of one
sample.

For example, suppose we have:

Age = 20
Salary = 50000
Experience = 2

We can represent one person as:

[20, 50000, 2]

This is called a feature vector.

In [2]:
import numpy as np

vector = np.array([20, 50000, 2])

print(vector)
print("Shape:", vector.shape)

[   20 50000     2]
Shape: (3,)


## 3. Vector in a Neural Network

Suppose a neuron receives 3 inputs:

x₁ = 2
x₂ = 4
x₃ = 6

We can represent them as a vector:

x = [2, 4, 6]

The neuron also has 3 weights:

w = [0.5, 0.2, 0.1]

The neuron calculates a weighted sum:

z = x₁w₁ + x₂w₂ + x₃w₃ + b

This can also be written using the dot product:

z = x · w + b

This operation is fundamental to neural networks.

In [3]:
x = np.array([2, 4, 6])

w = np.array([0.5, 0.2, 0.1])

b = 1

z = np.dot(x, w) + b

print("Weighted sum:", z)

Weighted sum: 3.4000000000000004


## 4. Dot Product

The dot product multiplies corresponding elements and then adds
the results.

For example:

x = [2, 4, 6]

w = [0.5, 0.2, 0.1]

x · w

= (2 × 0.5) + (4 × 0.2) + (6 × 0.1)

= 1 + 0.8 + 0.6

= 2.4

If we have a bias of 1:

z = 2.4 + 1

z = 3.4

This is the basic mathematical operation performed by a neuron.

## 5. Matrix

A matrix is a rectangular arrangement of numbers.

Example:

A =

[1  2  3]
[4  5  6]

This matrix has:

2 rows
3 columns

Therefore its shape is:

(2, 3)

In [4]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print("Shape:", matrix.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
